# Generated by Django 4.2.13 on 2024-06-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(default="TBD", max_length=15),
        ),
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="not-yet-image.png", upload_to="recipes"),
        ),
    ]
